# UI Colors (extended)
accent = "#686868"
cursor = "#b9b9b9"

# Primary colors
foreground = "#b9b9b9"
background = "#0f0f0f"

# Selection colors
selection_foreground = "#0f0f0f"
selection_background = "#b9b9b9"

# Normal colors (ANSI 0-7)
color0 = "#0f0f0f"
color1 = "#7c7c7c"
color2 = "#858e6c"
color3 = "#a0a0a0"
color4 = "#686868"
color5 = "#747474"
color6 = "#868686"
color7 = "#b9b9b9"

# Bright colors (ANSI 8-15)
color8 = "#525252"
color9 = "#7c7c7c"
color10 = "#8b8b8b"
color11 = "#a0a0a0"
color12 = "#686868"
color13 = "#747474"
color14 = "#868686"
color15 = "#ffffff"
